FROM {{ namespace }}/{{ image_prefix }}neutron-base:{{ tag }}
LABEL maintainer="{{ maintainer }}" name="{{ image_name }}" build-date="{{ build_date }}"

{% block neutron_l2gw_agent_header %}{% endblock %}

{% import "macros.j2" as macros with context %}

{% if install_type == 'binary' %}
    {% if base_distro in ['debian', 'ubuntu'] %}

        {% set neutron_l2gw_agent_packages = [
            'python-networking-l2gw'
        ] %}
    {% endif %}

{{ macros.install_packages(neutron_l2gw_agent_packages | customizable("packages")) }}

{% elif install_type == 'source' %}

{% set neutron_l2gw_agent_pip_packages = ['networking-l2gw'] %}

ADD plugins-archive /
RUN {{ macros.install_pip(neutron_l2gw_agent_pip_packages | customizable("pip_packages")) }}

{% endif %}

{{ macros.install_packages(neutron_l2gw_agent_packages | customizable("packages")) }}

{% block neutron_l2gw_agent_footer %}{% endblock %}
{% block footer %}{% endblock %}

USER neutron
